google_cloud_project: "agents-playground-474510"
google_cloud_location: "us-central1"
google_genai_use_vertexai: "True"
gemini_api_key: "flkdjfk"

sql:
  uri: "sqlite:///./session_db.sqlite"

fastapi:
  host: "0.0.0.0"
  port: 80
  log_level: "INFO"
  workers: 1

redis:
  url: null

oauth:
  redirect_uri: "http://localhost:8000/auth/callback"
