apiVersion: v1
kind: Secret
metadata:
  name: fastapi-agent-secrets
  labels:
    app: agent-service
type: Opaque
data:
  credentials.json: {{ .Values.secrets.googleServiceAccount | b64enc }}
  gemini-api-key: {{ .Values.secrets.geminiApiKey | b64enc }}
  google-app-client-id: {{ .Values.secrets.googleAppClientId | b64enc }}
  google-app-client-secret: {{ .Values.secrets.googleAppClientSecret | b64enc }}
  db-username: {{ .Values.secrets.dbUsername | b64enc }}
  db-password: {{ .Values.secrets.dbPassword | b64enc }}
  redis-url: {{ .Values.secrets.redisUrl | b64enc }}
